// <auto-generated />
namespace TheEvents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Anotheroneagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Anotheroneagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201705032342574_Another one again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
